services:
  rdos:
    build:
      context: .
      dockerfile: Dockerfile
    image: robotics-deployment:os-compiler
    container_name: rdos-compiler
    privileged: true
    network_mode: host
    pid: host
    ipc: host
    environment:
      - MACHINE=${MACHINE:-raspberrypi4-64}
#      - MACHINE=${MACHINE:-qemux86-64}
    volumes:
      - ./rdos:/home/user/rdos
    command: ["bash", "-c", "source oe-init-build-env && bitbake robotics-deployment-core"]
